### ISSUE TITLE
Gap bewteen the result of Colorimetry and visualization 

### ISSUE THREAD

**Issue by megumihayakawa85** [FilmColors/VIAN#259]
during the movie shows donald duck in visualization field Colorimetry shows already Micky Mouse showing up a little bit later in timeline. 

![Anmerkung 2020-03-09 145751](https://user-images.githubusercontent.com/58776405/76246220-8f9a4280-623d-11ea-9608-84296b519eb7.png)

![Anmerkung 2020-03-09 145813](https://user-images.githubusercontent.com/58776405/76246275-a80a5d00-623d-11ea-8d12-798d4bab1b5f.png)

**Comment by flueko** [comment]
Yes, there is a temporal off-set, it doesn't necessarily show the correct colorimetry for each frame. you have to scrub a little.

**Comment by ghalter** [comment]
Yes this is essentially expected, and as described in Slack, is due to the subsampling of the colorimetry. 
However, currently the Colorimetry shows the closest capture (which can be an later frame). In this case this leads to the confusion, as a palette is shown prior to the actual frame. 

Alternatively we could implement it such that always the last previous sample is visualized. 
I'm open to this, but can not say which is better. What do you think @flueko
