### ISSUE TITLE
Program did not start - problems with TensorFlow

### ISSUE THREAD

**Issue by mjwilleke** [FilmColors/VIAN#340]
Hello,

when I try to start the program, I get an error message (see attachment). Python 3.9.5 and the latest VLCx64 version are installed. 
I had VIAN already installed on another computer and no problems there.

Thank you for your help.

![fehlervian2](https://user-images.githubusercontent.com/85433550/120918291-024dd400-c6b4-11eb-82df-09cce96f651b.png)

**Comment by ghalter** [comment]
Hi @mjwilleke 
Thanks for the issue, it looks like it is related to this: 
https://github.com/pyinstaller/pyinstaller/issues/5898

I will investigate and look for a solution.

**Comment by rokm** [comment]
My guess would be that this is due to incomplete collection of VC runtime DLLs - PyInstaller `develop` has some fixes for this (pyinstaller/pyinstaller#5770, pyinstaller/pyinstaller#5778), but in this particular case, it seems that `concrt140.dll` is missing from the dist - so we'll need to update the inclusion list once again.

In the meantime, you can either manually ensure that `concrt140.dll` is collected, or ensure that [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) is installed on the target computer.

**Comment by mjwilleke** [comment]
I reinstalled VC and both Redistributable Visual Studio (x86 & x64) and a new error appeared:

![vianproblem2](https://user-images.githubusercontent.com/85433550/121802846-d9db5200-cc3e-11eb-9d03-5b79bfe81fcd.png)

**Comment by rokm** [comment]
Judging by the very first couple of lines, there was another `tensorflow`-related error preceding this one. Can you show complete traceback?

**Comment by mjwilleke** [comment]
> Judging by the very first couple of lines, there was another `tensorflow`-related error preceding this one. Can you show complete traceback?

Sorry I just manage to get screenshots, I hope that works:
![vianproblem3](https://user-images.githubusercontent.com/85433550/121803890-d8605880-cc43-11eb-8fd9-57b04f284500.png)

**Comment by rokm** [comment]
Are you by any chance trying to run this on a CPU that does not support AVX instruction set?

**Comment by mjwilleke** [comment]
> Are you by any chance trying to run this on a CPU that does not support AVX instruction set?

Yes, that correct. Is there any chance to get VIAN to run despite that?
Thank you for all help!

**Comment by rokm** [comment]
> Yes, that correct. Is there any chance to get VIAN to run despite that?

I guess that depends on whether VIAN requires `tensorflow` to work or not. 

But the official `tensorflow` builds require AVX, so the only way around the `tensorflow` import error would be to use unofficial/custom build of `tensorflow` that does not require AVX.

**Comment by ghalter** [comment]
Thanks rokm for all the insight. 

Yes, there is this possibility to run VIAN without tensorflow, however I currently don't have a build for windows which doesn't include it. Since I'm currently busy with other projects, I will create one with the next release. 
Until then, maybe it is possible for you to run VIAN with your own python interpreter?

**Comment by mjwilleke** [comment]
> Thanks rokm for all the insight.
> 
> Yes, there is this possibility to run VIAN without tensorflow, however I currently don't have a build for windows which doesn't include it. Since I'm currently busy with other projects, I will create one with the next release.
> Until then, maybe it is possible for you to run VIAN with your own python interpreter?

Thank you for all the work. I will continue to run VIAN on my office computer and look forward to the next release.

**Comment by pascalforny** [comment]
@mjwilleke could you please check if this tensorflow issue still persists? in the meantime, a new version has been released.
